-- MySQL Script generated by MySQL Workbench
-- Sat Nov  1 20:56:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Carrera` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Carrera` (
  `idCarrera` INT NOT NULL AUTO_INCREMENT,
  `nombreCarrera` VARCHAR(45) NULL,
  PRIMARY KEY (`idCarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombreCompleto` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `fechaRegistro` VARCHAR(45) NULL,
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `fk_Usuarios_Rol_idx` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Rol`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `mydb`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Postulante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Postulante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Postulante` (
  `idInformacionPostulante` INT NOT NULL AUTO_INCREMENT,
  `numeroControl` VARCHAR(45) NULL,
  `cvPath` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(45) NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Carrera_idCarrera` INT NOT NULL,
  PRIMARY KEY (`idInformacionPostulante`),
  INDEX `fk_InformacionPostulante_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  INDEX `fk_Postulante_Carrera1_idx` (`Carrera_idCarrera` ASC) VISIBLE,
  CONSTRAINT `fk_InformacionPostulante_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postulante_Carrera1`
    FOREIGN KEY (`Carrera_idCarrera`)
    REFERENCES `mydb`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estadoValidacionEmpresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estadoValidacionEmpresa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estadoValidacionEmpresa` (
  `idEstadoValidacionEmpresa` INT NOT NULL AUTO_INCREMENT,
  `estadoValidacionEmpresa` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoValidacionEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empresas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empresas` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nombreEmpresa` VARCHAR(45) NULL,
  `sector` VARCHAR(45) NULL,
  `representante` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `sitioWeb` VARCHAR(45) NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `estadoValidacionEmpresa_idEstadoValidacionEmpresa` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`),
  INDEX `fk_Empresas_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  INDEX `fk_Empresas_estadoValidacionEmpresa1_idx` (`estadoValidacionEmpresa_idEstadoValidacionEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Empresas_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empresas_estadoValidacionEmpresa1`
    FOREIGN KEY (`estadoValidacionEmpresa_idEstadoValidacionEmpresa`)
    REFERENCES `mydb`.`estadoValidacionEmpresa` (`idEstadoValidacionEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Habilidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Habilidades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Habilidades` (
  `idHabilidad` INT NOT NULL AUTO_INCREMENT,
  `nombreHabilidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idHabilidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Postulante_Habilidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Postulante_Habilidades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Postulante_Habilidades` (
  `idPostulante_Habilidad` INT NOT NULL AUTO_INCREMENT,
  `Postulante_idInformacionPostulante` INT NOT NULL,
  `Habilidades_idHabilidad` INT NOT NULL,
  PRIMARY KEY (`idPostulante_Habilidad`),
  INDEX `fk_Postulante_Habilidades_Postulante1_idx` (`Postulante_idInformacionPostulante` ASC) VISIBLE,
  INDEX `fk_Postulante_Habilidades_Habilidades1_idx` (`Habilidades_idHabilidad` ASC) VISIBLE,
  CONSTRAINT `fk_Postulante_Habilidades_Postulante1`
    FOREIGN KEY (`Postulante_idInformacionPostulante`)
    REFERENCES `mydb`.`Postulante` (`idInformacionPostulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postulante_Habilidades_Habilidades1`
    FOREIGN KEY (`Habilidades_idHabilidad`)
    REFERENCES `mydb`.`Habilidades` (`idHabilidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Experiencia_Laboral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Experiencia_Laboral` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Experiencia_Laboral` (
  `idExperiencia_Laboral` INT NOT NULL AUTO_INCREMENT,
  `puesto` VARCHAR(45) NULL,
  `empresa` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  `Postulante_idInformacionPostulante` INT NOT NULL,
  PRIMARY KEY (`idExperiencia_Laboral`),
  INDEX `fk_Experiencia_Laboral_Postulante1_idx` (`Postulante_idInformacionPostulante` ASC) VISIBLE,
  CONSTRAINT `fk_Experiencia_Laboral_Postulante1`
    FOREIGN KEY (`Postulante_idInformacionPostulante`)
    REFERENCES `mydb`.`Postulante` (`idInformacionPostulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Certificaciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Certificaciones` (
  `idCertificacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `organizacionEmisora` VARCHAR(45) NULL,
  `fecharObtencion` VARCHAR(45) NULL,
  `urlCredencial` VARCHAR(45) NULL,
  PRIMARY KEY (`idCertificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoValidacionVacante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EstadoValidacionVacante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EstadoValidacionVacante` (
  `idEstadoValidacionVacante` INT NOT NULL AUTO_INCREMENT,
  `estadoValidacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoValidacionVacante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoContrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoContrato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoContrato` (
  `idTipoContrato` INT NOT NULL AUTO_INCREMENT,
  `estadoContrato` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoContrato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoModalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoModalidad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoModalidad` (
  `idtipoModalidad` INT NOT NULL AUTO_INCREMENT,
  `nombreModalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipoModalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vacantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vacantes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vacantes` (
  `idVacante` INT NOT NULL AUTO_INCREMENT,
  `idEstadoValidacionVacante` INT NULL,
  `idTipoContrato` INT NULL,
  `titulo` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `requisitos` TEXT NULL,
  `ubicacion` VARCHAR(45) NULL,
  `Salario` DECIMAL NULL,
  `fechaPublicacion` TIMESTAMP NULL,
  `fechaLimite` DATE NULL,
  `Empresas_idEmpresa` INT NOT NULL,
  `EstadoValidacionVacante_idEstadoValidacionVacante` INT NOT NULL,
  `tipoContrato_idTipoContrato` INT NOT NULL,
  `tipoModalidad_idtipoModalidad` INT NOT NULL,
  PRIMARY KEY (`idVacante`),
  INDEX `fk_Vacantes_Empresas1_idx` (`Empresas_idEmpresa` ASC) VISIBLE,
  INDEX `fk_Vacantes_EstadoValidacionVacante1_idx` (`EstadoValidacionVacante_idEstadoValidacionVacante` ASC) VISIBLE,
  INDEX `fk_Vacantes_tipoContrato1_idx` (`tipoContrato_idTipoContrato` ASC) VISIBLE,
  INDEX `fk_Vacantes_tipoModalidad1_idx` (`tipoModalidad_idtipoModalidad` ASC) VISIBLE,
  CONSTRAINT `fk_Vacantes_Empresas1`
    FOREIGN KEY (`Empresas_idEmpresa`)
    REFERENCES `mydb`.`Empresas` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vacantes_EstadoValidacionVacante1`
    FOREIGN KEY (`EstadoValidacionVacante_idEstadoValidacionVacante`)
    REFERENCES `mydb`.`EstadoValidacionVacante` (`idEstadoValidacionVacante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vacantes_tipoContrato1`
    FOREIGN KEY (`tipoContrato_idTipoContrato`)
    REFERENCES `mydb`.`tipoContrato` (`idTipoContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vacantes_tipoModalidad1`
    FOREIGN KEY (`tipoModalidad_idtipoModalidad`)
    REFERENCES `mydb`.`tipoModalidad` (`idtipoModalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoPostulacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EstadoPostulacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EstadoPostulacion` (
  `idEstadoPostulacion` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoPostulacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Postulaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Postulaciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Postulaciones` (
  `idPostulacion` INT NOT NULL AUTO_INCREMENT,
  `fechaPostulacion` TIMESTAMP NULL,
  `Postulante_idInformacionPostulante` INT NOT NULL,
  `Vacantes_idVacante` INT NOT NULL,
  `EstadoPostulacion_idEstadoPostulacion` INT NOT NULL,
  PRIMARY KEY (`idPostulacion`),
  INDEX `fk_Postulaciones_Postulante1_idx` (`Postulante_idInformacionPostulante` ASC) VISIBLE,
  INDEX `fk_Postulaciones_Vacantes1_idx` (`Vacantes_idVacante` ASC) VISIBLE,
  INDEX `fk_Postulaciones_EstadoPostulacion1_idx` (`EstadoPostulacion_idEstadoPostulacion` ASC) VISIBLE,
  CONSTRAINT `fk_Postulaciones_Postulante1`
    FOREIGN KEY (`Postulante_idInformacionPostulante`)
    REFERENCES `mydb`.`Postulante` (`idInformacionPostulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postulaciones_Vacantes1`
    FOREIGN KEY (`Vacantes_idVacante`)
    REFERENCES `mydb`.`Vacantes` (`idVacante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postulaciones_EstadoPostulacion1`
    FOREIGN KEY (`EstadoPostulacion_idEstadoPostulacion`)
    REFERENCES `mydb`.`EstadoPostulacion` (`idEstadoPostulacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Postulante_Certificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Postulante_Certificacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Postulante_Certificacion` (
  `Postulante_idInformacionPostulante` INT NOT NULL AUTO_INCREMENT,
  `Certificaciones_idCertificacion` INT NOT NULL,
  INDEX `fk_Postulante_Certificacion_Postulante1_idx` (`Postulante_idInformacionPostulante` ASC) VISIBLE,
  INDEX `fk_Postulante_Certificacion_Certificaciones1_idx` (`Certificaciones_idCertificacion` ASC) VISIBLE,
  PRIMARY KEY (`Postulante_idInformacionPostulante`, `Certificaciones_idCertificacion`),
  CONSTRAINT `fk_Postulante_Certificacion_Postulante1`
    FOREIGN KEY (`Postulante_idInformacionPostulante`)
    REFERENCES `mydb`.`Postulante` (`idInformacionPostulante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postulante_Certificacion_Certificaciones1`
    FOREIGN KEY (`Certificaciones_idCertificacion`)
    REFERENCES `mydb`.`Certificaciones` (`idCertificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
